# Generated by Django 3.1 on 2020-12-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('value_from', models.IntegerField()),
                ('value_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=256)),
                ('rule_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleRunTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=256)),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.rules')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('value_from', models.IntegerField()),
                ('value_to', models.IntegerField()),
                ('tag', models.CharField(max_length=256)),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.rules')),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.FloatField()),
                ('purchase_order_line', models.FloatField()),
                ('supplier_name', models.CharField(max_length=256)),
                ('spend', models.FloatField()),
                ('group_name', models.CharField(max_length=256)),
                ('supplier_tag', models.CharField(max_length=256)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.document')),
            ],
        ),
    ]
