# Generated by Django 3.1 on 2020-12-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_enrichment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=256)),
                ('rule_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('parameter', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=256)),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.document')),
            ],
        ),
    ]
