# Generated by Django 3.1 on 2020-12-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_enrichment', '0002_rulecondition_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.rules'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='value',
            field=models.IntegerField(),
        ),
    ]
