# Generated by Django 3.1 on 2020-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_enrichment', '0003_auto_20201209_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulecondition',
            old_name='value',
            new_name='value_from',
        ),
        migrations.RemoveField(
            model_name='rulecondition',
            name='parameter',
        ),
        migrations.AddField(
            model_name='lines',
            name='group_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulecondition',
            name='value_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
