# Generated by Django 3.1 on 2020-12-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_enrichment', '0004_auto_20201209_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleRunTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=256)),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_enrichment.rules')),
            ],
        ),
    ]
