# Generated by Django 3.1 on 2020-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_enrichment', '0005_ruleruntrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.IntegerField()),
                ('value_to', models.IntegerField()),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
    ]
